### ISSUE TITLE
Getter / Setter overrides

### ISSUE THREAD

**Issue by jgraup** [ericandrewlewis/wp-custom-css-per-post#4]
Do you think it's possible / practical to allow for getter/setter overrides?

Currently you're using `get_post_meta` and `update_post_meta`. It would be nice to have the ability to use [ACF](http://www.advancedcustomfields.com/pro/)'s [get_field()](http://www.advancedcustomfields.com/resources/get_field/) and [update_field](http://www.advancedcustomfields.com/resources/update_field/).

It might not make sense for this particular plugin but it's a great example on how it might be possible to integrate other types of custom fields or other data already set using ACF.

**Comment by ericandrewlewis** [comment]
Hi @jgraup, thanks a lot for this suggestion. For now, this repo is intended to be educational, so I'm going to say no to feature requests. Feel free to fork and do with as you please though :smile:
